# B2B website service
apiVersion: v1
kind: Service
metadata:
  name: dev-website-b2b-service
  namespace: dev
  labels:
    app: dev-website-b2b
spec:
  type: NodePort
  selector:
    app: dev-website-b2b
  ports:
    - name: http-svc
      protocol: TCP
      port: 80
      targetPort: http
