export const priceArr = [
    {
      title: "Title",
      label: "Application",
      href: "#intro",
      btnText: "",
      links: [
        "Affiliate network",
        "Reservation management",
        "Daily business management",
        "Payment solution",
        "Website integration",
        "Online booking tools",
        "Instant invoicing",
        "Flight tracking",
        "Weekly feature updates",
        "User friendly",
        "No office required",
        "Run your business on the go",
        "Increase earnings",
        "Cancel anytime",
      ],
      price: "$59.99",
      priceText: "/ month",
    },
    {
      title: "Title",
      label: "Special",
      href: "",
      btnText: "Claim now",
      links: [
        "Website landing page & SEO",
        "Customized website booking tool (Widget)",
        "12-month mobile app subscription",
      ],
      price: "$599.00",
      priceLabel: "Limited time only",
    },
];