# B2B website deployment
# https://gallery.ecr.aws/nginx/nginx customizations
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-b2b-deployment
  namespace: prod
  labels:
    app: website-b2b
spec:
  selector:
    matchLabels:
      app: website-b2b
  replicas: 2

  template:
    metadata:
      labels:
        app: website-b2b
    spec:
      restartPolicy: Always
      containers:
        - name: website-b2b-nginx
          image: 264065980716.dkr.ecr.us-east-2.amazonaws.com/prod-website-b2b:v2.9.0
          imagePullPolicy: Always
          resources:
            limits:
              memory: "256Mi"
              cpu: "150m"
          env:
            - name: NGINX_ENTRYPOINT_QUIET_LOGS
              value: "0"
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
